trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  SolutionPath: '*/**.sln'

stages:  
- stage: Build
  displayName: Build solution
  jobs:  
  - job: Build
    displayName: Build and publish solution
    steps:
    - task: UseDotNet@2      
      inputs:
        packageType: 'sdk'
        version: '5.0.x'
      displayName: 'Use .NET Core SDK 5.0.x'
      condition: 
    - task: UseDotNet@2
      inputs:
        version: '3.1.x'
        packageType: sdk
        includePreviewVersions: false 
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'
    # - task: DotNetCoreCLI@2
    #   inputs:
    #     command: 'restore'
    #     projects: '$(SolutionPath)'
    #   displayName: 'Restore NuGet packages'
 
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '$(SolutionPath)'
      displayName: 'Build solution'
        
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        zipAfterPublish: true
        projects: '$(SolutionPath)'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
      displayName: 'Publish solution'
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'b2bee-dev-001 (85581b53-f177-43f0-a203-80129dfa772b)'
        appType: 'functionApp'
        appName: 'fn-c-kafa-api-001'
        package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
        deploymentMethod: 'auto'